created: 2026-08-04T14:31:12.293Z
updated: 2026-08-04T14:31:12.576Z
update_count: 2
last_field: diagram
kind: nested-class
title: backend-api
children:
  - analysis-routes
  - auth-routes
  - domain-routes
  - history-routes
  - security
  - warmup-routes
parentPath: []
